### ISSUE TITLE
it will not work on version 1.2

### ISSUE THREAD

**Issue by alsemany** [vixh/nginx-webmin#3]
when I upgraded nginx 0.7.6 to 1.2 the module disappears from virualmin 

even if I tried to install a domain manually from webmin 

it faild and I got this message

Can't use string ("/home/XXXXXX/public_html") as an ARRAY ref while "strict refs" in use at virtualmin-nginx-lib.pl line 247.

**Comment by n00b2pr0** [comment]
I'm seeing the same issue with 1.2

**Comment by mlchai** [comment]
I am also getting this.

**Comment by mishatatinets** [comment]
Some here. It is not working with nginx 1.2.3

**Comment by lancepioch** [comment]
Running nginx 1.4.1 and it still fails.

**Comment by motomod** [comment]
Comment out "use strict" in /usr/share/webmin/virtualmin-nginx/virtualmin-nginx-lib.pl

**Comment by alsemany** [comment]
Thank you for the replies it's an old issue and I think that all the current installation working great now, 

> Comment out "use strict" in /usr/share/webmin/virtualmin-nginx/virtualmin-nginx-lib.pl
 :+1: 1  

I will close the issue
